global:
  scrape_interval: 15s

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'juice-shop'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:4000'] # Juice Shop default port

  - job_name: 'node-exporter'  # For system monitoring
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']